
development:
  adapter: postgresql
  database: db_dev
  pool: 5
  timeout: 5000
  encoding: unicode
  host: localhost
  username: jonwyatt
  port: 5432

test:
  adapter: postgresql
  database: db_test
  pool: 5
  timeout: 5000
  encoding: unicode
  host: localhost
  username: jonwyatt
  port: 5432

production:
  adapter: postgresql
  database: db_production
  pool: 5
  timeout: 5000
  encoding: unicode
  host: localhost
  username: jonwyatt
  port: 5432